const CARDS = [
  { id: "c1", name: "Chase Sapphire" },
  { id: "c2", name: "Amex Gold" },
  { id: "c3", name: "Citi Double Cash" },
]

const TRANSACTIONS = [
  {
    id: "t1",
    date: "2025-03-05",
    merchant: "Con Edison",
    note: "Electric bill",
    amount: 87.4,
    cardId: "c1",
    label: "necessary",
  },
  {
    id: "t2",
    date: "2025-03-08",
    merchant: "Trader Joe's",
    note: "Groceries",
    amount: 63.15,
    cardId: "c1",
    label: "necessary",
  },
  {
    id: "t3",
    date: "2025-03-12",
    merchant: "Netflix",
    note: "Streaming",
    amount: 15.99,
    cardId: "c2",
    label: "useful",
  },
  {
    id: "t4",
    date: "2025-03-15",
    merchant: "Zara",
    note: "Jacket",
    amount: 89.0,
    cardId: "c2",
    label: "impulsive",
  },
  {
    id: "t5",
    date: "2025-03-20",
    merchant: "Spotify",
    note: "Music",
    amount: 10.99,
    cardId: "c2",
    label: "useful",
  },
  {
    id: "t6",
    date: "2025-03-22",
    merchant: "Amazon",
    note: "Desk lamp",
    amount: 34.5,
    cardId: "c3",
    label: "",
  },
  {
    id: "t7",
    date: "2025-03-28",
    merchant: "Shake Shack",
    note: "Lunch",
    amount: 22.75,
    cardId: "c1",
    label: "impulsive",
  },
  {
    id: "t8",
    date: "2025-04-01",
    merchant: "Con Edison",
    note: "Electric bill",
    amount: 82.1,
    cardId: "c1",
    label: "necessary",
  },
  {
    id: "t9",
    date: "2025-04-03",
    merchant: "Trader Joe's",
    note: "Groceries",
    amount: 71.2,
    cardId: "c1",
    label: "necessary",
  },
  {
    id: "t10",
    date: "2025-04-05",
    merchant: "Netflix",
    note: "Streaming",
    amount: 15.99,
    cardId: "c2",
    label: "useful",
  },
  {
    id: "t11",
    date: "2025-04-07",
    merchant: "Airbnb",
    note: "Weekend trip",
    amount: 210.0,
    cardId: "c3",
    label: "useful",
  },
  {
    id: "t12",
    date: "2025-04-09",
    merchant: "Amazon",
    note: "Impulse buy",
    amount: 54.99,
    cardId: "c3",
    label: "impulsive",
  },
  {
    id: "t13",
    date: "2025-04-10",
    merchant: "CVS",
    note: "Medicine",
    amount: 18.4,
    cardId: "c2",
    label: "necessary",
  },
]
